resolver: lts-7.12
packages:
- '.'
- location:
    git: https://github.com/scrive/log.git
    commit: 5298533b243869220ee585f89187500aba54093f
  subdirs:
  - log-elasticsearch
  extra-dep: true
extra-deps:
- log-base-0.7
- bloodhound-0.12.0.0
- hpqtypes-1.5.1.1
compiler-check: newer-minor
